### PR TITLE
feature extaction

### PR DESCRIPTION
**Pull request by aoussou**
The original BERT model does not easily allow to use the Japanese version BERT for feature extraction,
mostly because the tokenization is different.

However, only a simple fix is required .

(A bert_config.json file is necessary. I have create that file. In case you accept the request, let me know if you want me to provide it as well).

The submodule is the latest version of BERT.

### CODE REVIEW

**Comment by yoheikikuta** [comment]
Sorry for the late reply.
Let me check the PR.

**Comment by yoheikikuta** [comment]
@aoussou 
Thanks for your contribution, I got the points.

In this repository I provided a file corresponding to bert_config.json as a temp file in notebooks, as did in https://github.com/yoheikikuta/bert-japanese/blob/master/notebook/finetune-to-livedoor-corpus.ipynb.

So I'd appreciate if you could provide a notebook like this that includes feature extraction codes and some example to check the validity of the feature extraction.

If it is difficult, let me know. 
I will just update the submodule (and I will create the notebook if I have time).

**Comment by aoussou** [comment]
@yoheikikuta 

Thank you for your reply!
I will do my best to do as you you have asked, however I need to clarify a number of points.

1. `some example to check the validity of the feature extraction`

Sure, what kind of example should I use, and how would you like me to check the validity?

2. `provide a notebook like this that includes feature extraction codes`

I created a python script for myself, so I should easily be able to turn it into a Python notebook. However, to make this script work, I had to change other functions in the repository, so I don't think in that case it's a good idea. 

Isn't it better to run it exactly the same way as the original BERT repository?

# Sentence A and Sentence B are separated by the ||| delimiter for sentence
# pair tasks like question answering and entailment.
# For single sentence inputs, put one sentence per line and DON'T use the
# delimiter.
echo 'Who was Jim Henson ? ||| Jim Henson was a puppeteer' > /tmp/input.txt

```
python extract_features.py \
  --input_file=/tmp/input.txt \
  --output_file=/tmp/output.jsonl \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --layers=-1,-2,-3,-4 \
  --max_seq_length=128 \
  --batch_size=8
```

3. `In this repository I provided a file corresponding to bert_config.json as a temp file in notebooks`

Yes, in fact I used a hacked version of that code to create the config file.
Would you like me to provide the script that export that file?

**Comment by yoheikikuta** [comment]
@aoussou 

> Sure, what kind of example should I use, and how would you like me to check the validity?

Too good question to answer :)
At first I planned to create an example that uses extracted features and solve the same classification problem as fine-tuning notebook to check the validity of the features.

But it's a bit lazy task.
Okay, how about providing a notebook including just a few examples of feature extractions? (like https://github.com/yoheikikuta/bert-japanese/blob/master/notebook/check-trained-tokenizer.ipynb).

> Would you like me to provide the script to export that file?

No thanks for now, the reason I didn't provide the `bert_config.json` is to put all the config information into the `config.ini`.
But If you provide the file and ALSO modify the corresponding parts in `finetune-to-livedoor-corpus.ipynb`, `run_classifier.py` and `run_pretraining.py`, I'll accept it.

**Comment by aoussou** [comment]
@yoheikikuta 

I created a notebook as requested: https://github.com/xrosriver/bert-japanese/blob/dev/feature_extraction/notebook/check-extract-features.ipynb
Please check it when you have time.

**Comment by yoheikikuta** [comment]
@aoussou 
Thanks!
It's cool, but I have one more favor to ask.
Could you add cells that read the output json file and print the shapes of the extracted features, which helps reader to roughly understand how to treat the output before executing the notebook?

**Comment by aoussou** [comment]
@yoheikikuta 

Done.

**Comment by yoheikikuta** [comment]
@aoussou 
MERGED. Thanks for your contribution!

**Pull request merged**
