### PR TITLE
Fix path to WikiExtractor.py

### PR DESCRIPTION
**Pull request by vochicong**
README.md に書いてある通りにコマンドを実行した場合のパスが合うように修正
$ python3 src/data-download-and-extract.py

### CODE REVIEW

**Comment by yoheikikuta** [comment]
I guess this change should be merged into https://github.com/yoheikikuta/bert-japanese/pull/18, right?

**Comment by vochicong** [comment]
#17 and #18 are somehow independent, you can choose whether to merge each one.

**Comment by yoheikikuta** [comment]
But the current Dockerfile provides `/wikiextractor` and `/work/src/data-download-and-extract.py`, so your modified path looks not working.
Did you check your script in a docker container?

**Comment by vochicong** [comment]
> Did you check your script in a docker container?
Not yet.

**Comment by vochicong** [comment]
@yoheikikuta You are right.

I've merged #17 into #18.

**Pull request closed without merging**
